# from ProcessImage import Load_Image, Resize_Image, Detect_box, Save_Image, Process_Image
# import matplotlib.pyplot as plt
# import numpy as np
# import cv2
# import os


# from_path = "/home/ramiz/signatureDetection/Signs/Originals/Bengali/"
# to_path = "/home/ramiz/signatureDetection/Signs/Processed-Original/Bengali/"

# counta = Process_Image(from_path, to_path, '0', 1, first_name="Ben_00",  extension='.jpg')
# print("\n0 completed")

# counta = Process_Image(from_path, to_path, '01', counta, first_name="Ben_00",  extension='.jpg')
# print("\n01 completed")
# counta = Process_Image(from_path, to_path, '02', counta, first_name="Ben_00",  extension='.jpg')
# print("\n02 completed")
# count = Process_Image(from_path, to_path, '03', 79, first_name="Ben_00",  extension='.jpg')
# print("\n03 completed")
# count = Process_Image(from_path, to_path, '04', count, first_name="Ben_0",  extension='.jpg')
# print("\n04 completed")
# count = Process_Image(from_path, to_path, '05', count, first_name="Ben_0",  extension='.jpg')
# print("\n05 completed")
# count = Process_Image(from_path, to_path, '06', count, first_name="Ben_0",  extension='.jpg')
# print("\n06 completed")
# count = Process_Image(from_path, to_path, '07', count, first_name="Ben_0",  extension='.jpg')
# print("\n07 completed")
# count = Process_Image(from_path, to_path, '08', count, first_name="Ben_0",  extension='.jpg')
# print("\n08 completed")
# count = Process_Image(from_path, to_path, '09', count, first_name="Ben_0",  extension='.jpg')
# print("\n09 completed")
# count = Process_Image(from_path, to_path, '10', count, first_name="Ben_0",  extension='.jpg')
# print("\n10 completed")


# count = Process_Image(from_path, to_path, '11', count, first_name="Ben_0",  extension='.jpg')
# print("\n11 completed")
# count = Process_Image(from_path, to_path, '12', count, first_name="Ben_0",  extension='.jpg')
# print("\n12 completed")
# count = Process_Image(from_path, to_path, '13', count, first_name="Ben_0",  extension='.jpg')
# print("\n13 completed")
# count = Process_Image(from_path, to_path, '14', count, first_name="Ben_0",  extension='.jpg')
# print("\n14 completed")
# count = Process_Image(from_path, to_path, '15', count, first_name="Ben_0",  extension='.jpg')
# print("\n15 completed")
# count = Process_Image(from_path, to_path, '16', count, first_name="Ben_0",  extension='.jpg')
# print("\n16 completed")
# count = Process_Image(from_path, to_path, '17', count, first_name="Ben_0",  extension='.jpg')
# print("\n17 completed")
# count = Process_Image(from_path, to_path, '18', count, first_name="Ben_0",  extension='.jpg')
# print("\n18 completed")
# count = Process_Image(from_path, to_path, '19', count, first_name="Ben_0",  extension='.jpg')
# print("\n19 completed")
# count = Process_Image(from_path, to_path, '20', count, first_name="Ben_0",  extension='.jpg')
# print("\n20 completed")

# count = Process_Image(from_path, to_path, '21', count, first_name="Ben_0",  extension='.jpg')
# print("\n21 completed")
# count = Process_Image(from_path, to_path, '22', count, first_name="Ben_0",  extension='.jpg')
# print("\n22 completed")
# count = Process_Image(from_path, to_path, '23', count, first_name="Ben_0",  extension='.jpg')
# print("\n23 completed")
# count = Process_Image(from_path, to_path, '24', count, first_name="Ben_0",  extension='.jpg')
# print("\n24 completed")
# count = Process_Image(from_path, to_path, '25', count, first_name="Ben_0",  extension='.jpg')
# print("\n25 completed")
# count = Process_Image(from_path, to_path, '26', count, first_name="Ben_0",  extension='.jpg')
# print("\n26 completed")
# count = Process_Image(from_path, to_path, '27', count, first_name="Ben_0",  extension='.jpg')
# print("\n27 completed")
# count = Process_Image(from_path, to_path, '28', count, first_name="Ben_0",  extension='.jpg')
# print("\n28 completed")
# count = Process_Image(from_path, to_path, '29', count, first_name="Ben_0",  extension='.jpg')
# print("\n29 completed")
# count = Process_Image(from_path, to_path, '30', count, first_name="Ben_0",  extension='.jpg')
# print("\n30 completed")


# count = Process_Image(from_path, to_path, '31', count, first_name="Ben_0",  extension='.jpg')
# print("\n31 completed")
# count = Process_Image(from_path, to_path, '32', count, first_name="Ben_",  extension='.jpg')
# print("\n32 completed")
# count = Process_Image(from_path, to_path, '33', count, first_name="Ben_",  extension='.jpg')
# print("\n33 completed")
# count = Process_Image(from_path, to_path, '34', count, first_name="Ben_",  extension='.jpg')
# print("\n34 completed")
# count = Process_Image(from_path, to_path, '35', count, first_name="Ben_",  extension='.jpg')
# print("\n35 completed")
# count = Process_Image(from_path, to_path, '36', count, first_name="Ben_",  extension='.jpg')
# print("\n36 completed")
# count = Process_Image(from_path, to_path, '37', count, first_name="Ben_",  extension='.jpg')
# print("\n37 completed")
# count = Process_Image(from_path, to_path, '38', count, first_name="Ben_",  extension='.jpg')
# print("\n38 completed")
# count = Process_Image(from_path, to_path, '39', count, first_name="Ben_",  extension='.jpg')
# print("\n39 completed")
# count = Process_Image(from_path, to_path, '40', count, first_name="Ben_",  extension='.jpg')
# print("\n40 completed")


# count = Process_Image(from_path, to_path, '41', count, first_name="Ben_",  extension='.jpg')
# print("\n41 completed")
# count = Process_Image(from_path, to_path, '42', count, first_name="Ben_",  extension='.jpg')
# print("\n42 completed")
# count = Process_Image(from_path, to_path, '43', count, first_name="Ben_",  extension='.jpg')
# print("\n43 completed")
# count = Process_Image(from_path, to_path, '44', count, first_name="Ben_",  extension='.jpg')
# print("\n44 completed")
# count = Process_Image(from_path, to_path, '45', count, first_name="Ben_",  extension='.jpg')
# print("\n45 completed")
# count = Process_Image(from_path, to_path, '46', count, first_name="Ben_",  extension='.jpg')
# print("\n46 completed")
# count = Process_Image(from_path, to_path, '47', count, first_name="Ben_",  extension='.jpg')
# print("\n47 completed")
# count = Process_Image(from_path, to_path, '48', count, first_name="Ben_",  extension='.jpg')
# print("\n48 completed")
# count = Process_Image(from_path, to_path, '49', count, first_name="Ben_",  extension='.jpg')
# print("\n49 completed")
# count = Process_Image(from_path, to_path, '50', count, first_name="Ben_",  extension='.jpg')
# print("\n50 completed")


# count = Process_Image(from_path, to_path, '51', count, first_name="Ben_",  extension='.jpg')
# print("\n51 completed")
# count = Process_Image(from_path, to_path, '52', count, first_name="Ben_",  extension='.jpg')
# print("\n52 completed")
# count = Process_Image(from_path, to_path, '53', count, first_name="Ben_",  extension='.jpg')
# print("\n53 completed")
# count = Process_Image(from_path, to_path, '54', count, first_name="Ben_",  extension='.jpg')
# print("\n54 completed")
# count = Process_Image(from_path, to_path, '55', count, first_name="Ben_",  extension='.jpg')
# print("\n55 completed")
# count = Process_Image(from_path, to_path, '56', count, first_name="Ben_",  extension='.jpg')
# print("\n56 completed")
# count = Process_Image(from_path, to_path, '57', count, first_name="Ben_",  extension='.jpg')
# print("\n57 completed")
# count = Process_Image(from_path, to_path, '58', count, first_name="Ben_",  extension='.jpg')
# print("\n58 completed")
# count = Process_Image(from_path, to_path, '59', count, first_name="Ben_",  extension='.jpg')
# print("\n59 completed")
# count = Process_Image(from_path, to_path, '60', count, first_name="Ben_",  extension='.jpg')
# print("\n60 completed")


# count = Process_Image(from_path, to_path, '61', count, first_name="Ben_",  extension='.jpg')
# print("\n61 completed")
# count = Process_Image(from_path, to_path, '62', count, first_name="Ben_",  extension='.jpg')
# print("\n62 completed")
# count = Process_Image(from_path, to_path, '63', count, first_name="Ben_",  extension='.jpg')
# print("\n63 completed")
# count = Process_Image(from_path, to_path, '64', count, first_name="Ben_",  extension='.jpg')
# print("\n64 completed")
# count = Process_Image(from_path, to_path, '65', count, first_name="Ben_",  extension='.jpg')
# print("\n65 completed")
# count = Process_Image(from_path, to_path, '66', count, first_name="Ben_",  extension='.jpg')
# print("\n66 completed")
# count = Process_Image(from_path, to_path, '67', count, first_name="Ben_",  extension='.jpg')
# print("\n67 completed")
# count = Process_Image(from_path, to_path, '68', count, first_name="Ben_",  extension='.jpg')
# print("\n68 completed")
# count = Process_Image(from_path, to_path, '69', count, first_name="Ben_",  extension='.jpg')
# print("\n69 completed")
# count = Process_Image(from_path, to_path, '70', count, first_name="Ben_",  extension='.jpg')
# print("\n70 completed")


# count = Process_Image(from_path, to_path, '71', count, first_name="Ben_",  extension='.jpg')
# print("\n71 completed")
# count = Process_Image(from_path, to_path, '72', count, first_name="Ben_",  extension='.jpg')
# print("\n72 completed")
# count = Process_Image(from_path, to_path, '73', count, first_name="Ben_",  extension='.jpg')
# print("\n73 completed")
# count = Process_Image(from_path, to_path, '74', count, first_name="Ben_",  extension='.jpg')
# print("\n74 completed")
# count = Process_Image(from_path, to_path, '75', count, first_name="Ben_",  extension='.jpg')
# print("\n75 completed")
# count = Process_Image(from_path, to_path, '76', count, first_name="Ben_",  extension='.jpg')
# print("\n76 completed")


# print("|||COMPLETED|||"

