from ProcessImage import Load_Image, Detect_box, Resize_Image
import matplotlib.pyplot as plt
import os 
import numpy as np
import cv2

hindi_01 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/01")
hindi_02 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/02")
hindi_03 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/03")
hindi_04 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/04")
hindi_05 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/05")
hindi_06 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/06")
hindi_07 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/07")
hindi_08 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/08")
hindi_09 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/09")
hindi_10 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/10")
hindi_11 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/11")
hindi_12 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/12")
hindi_13 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/13")
hindi_14 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/14")
hindi_15 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/15")
hindi_16 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/16")
hindi_17 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/17")
hindi_18 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/18")
hindi_19 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/19")
hindi_20 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/20")
hindi_21 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/21")
hindi_22 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/22")
hindi_23 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/23")
hindi_24 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/24")
hindi_25 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/25")
hindi_26 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/26")
hindi_27 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/27")
hindi_28 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/28")
hindi_29 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/29")
hindi_30 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/30")
hindi_31 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/31")
hindi_32 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/32")
hindi_33 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/33")
hindi_34 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/34")
hindi_35 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/35")
hindi_36 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/36")
hindi_37 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/37")
hindi_38 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/38")
hindi_39 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/39")
hindi_40 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/40")
hindi_41 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/41")
hindi_42 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/42")
hindi_43 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/43")
hindi_44 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/44")
hindi_45 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/45")
hindi_46 = Load_Image("/home/ramiz/signatureDetection/Signs/Originals/Hindi/46")

for i in range(len(hindi_40)):
	print(hindi_40[i].shape)
